CREATE TABLE meet_up
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        timestamp,
    description VARCHAR(255),
    organizer   VARCHAR(255),
    location    VARCHAR(255),
    theme       VARCHAR(255),
    CONSTRAINT meet_up_pkey PRIMARY KEY (id)
);